#!/bin/bash -l
#BSUB -J TPE_Medical_Data_and_Hospital_Readmissions_12
#BSUB -n 1
#BSUB -q short
#BSUB -o out_%J.log
#BSUB -e err_%J.log

source /usr/local/apps/miniconda20240526/etc/profile.d/conda.sh
conda activate /share/tjmenzie/kgangul/SEOptBench/smac_env

cd /share/tjmenzie/kgangul/SEOptBench/experiments
python3 experiment_runner_cluster.py --name TPE --repeats 20 --runs_output_folder ../results/results_TPE --logging_folder ../logging/logging_TPE --output_directory ../results/tmp/TPE_tmp --datasets ../moot/optimize/health_data/Medical_Data_and_Hospital_Readmissions.csv --budget 12
