#!/bin/bash -l
#BSUB -J TPE_Health-Commits0005_6
#BSUB -n 1
#BSUB -q short
#BSUB -o out_%J.log
#BSUB -e err_%J.log

source /usr/local/apps/miniconda20240526/etc/profile.d/conda.sh
conda activate /share/tjmenzie/kgangul/SEOptBench/smac_env

cd /share/tjmenzie/kgangul/SEOptBench/experiments
python3 experiment_runner_cluster.py --name TPE --repeats 20 --runs_output_folder ../results/results_TPE --logging_folder ../logging/logging_TPE --output_directory ../results/tmp/TPE_tmp --datasets ../moot/optimize/hpo/Health-Commits0005.csv --budget 6
