#!/bin/bash -l
#BSUB -J Active_Learning_SS-E_12
#BSUB -n 1
#BSUB -q short
#BSUB -W 120
#BSUB -o out_%J.log
#BSUB -e err_%J.log

source /usr/local/apps/miniconda20240526/etc/profile.d/conda.sh
conda activate /share/tjmenzie/kgangul/SEOptBench/smac_env

cd /share/tjmenzie/kgangul/SEOptBench/experiments
python3 experiment_runner_cluster.py --name Active_Learning --repeats 20 --runs_output_folder ../results/results_Active_Learning --logging_folder ../logging/logging_Active_Learning --output_directory ../results/tmp/Active_Learning_tmp --datasets ../moot/optimize/config/SS-E.csv --budget 12
