#!/bin/bash -l
#BSUB -J Active_Learning_FM-500-100-1.00-SAT-1_6
#BSUB -n 1
#BSUB -q short
#BSUB -o out_%J.log
#BSUB -e err_%J.log

source /usr/local/apps/miniconda20240526/etc/profile.d/conda.sh
conda activate /share/tjmenzie/kgangul/SEOptBench/smac_env

cd /share/tjmenzie/kgangul/SEOptBench/experiments
python3 experiment_runner_cluster.py --name Active_Learning --repeats 20 --runs_output_folder /share/tjmenzie/kgangul/results/results_Active_Learning --logging_folder /share/tjmenzie/kgangul/logging/logging_Active_Learning --output_directory /share/tjmenzie/kgangul/results/tmp/Active_Learning_tmp --datasets ../moot/optimize/binary_config/FM-500-100-1.00-SAT-1.csv --budget 6
