#!/bin/bash -l
#BSUB -J KMPLUSPLUS_A2C_CartPole_24
#BSUB -n 1
#BSUB -q short
#BSUB -o out_%J.log
#BSUB -e err_%J.log

source /usr/local/apps/miniconda20240526/etc/profile.d/conda.sh
conda activate /share/tjmenzie/kgangul/SEOptBench/smac_env

cd /share/tjmenzie/kgangul/SEOptBench/experiments
python3 experiment_runner_cluster.py --name KMPlusPlus --repeats 20 --runs_output_folder /share/tjmenzie/kgangul/results/results_KMPlusPlus --logging_folder /share/tjmenzie/kgangul/logging/logging_KMPlusPlus --output_directory /share/tjmenzie/kgangul/results/tmp/KMPlusPlus_tmp --datasets ../moot/optimize/rl/A2C_CartPole.csv --budget 24
