#!/bin/bash -l
#BSUB -J DEHB_Health-Commits0008_200
#BSUB -n 1
#BSUB -q short
#BSUB -W 120
#BSUB -o out_%J.log
#BSUB -e err_%J.log

source /usr/local/apps/miniconda20240526/etc/profile.d/conda.sh
conda activate /share/tjmenzie/kgangul/SEOptBench/smac_env

cd /share/tjmenzie/kgangul/SEOptBench/experiments
python3 experiment_runner_cluster.py --name DEHB --repeats 20 --runs_output_folder ../results/results_DEHB --logging_folder ../logging/logging_DEHB --output_directory ../results/tmp/DEHB_tmp --datasets ../moot/optimize/hpo/Health-Commits0008.csv --budget 200
