#!/bin/bash -l
#BSUB -J DE_Health-ClosedPRs0010_50
#BSUB -n 1
#BSUB -q short
#BSUB -W 120
#BSUB -o out_%J.log
#BSUB -e err_%J.log

source /usr/local/apps/miniconda20240526/etc/profile.d/conda.sh
conda activate /share/tjmenzie/kgangul/SEOptBench/smac_env

cd /share/tjmenzie/kgangul/SEOptBench/experiments
python3 experiment_runner_cluster.py --name DE --repeats 20 --runs_output_folder ../results/results_DE --logging_folder ../logging/logging_DE --output_directory ../results/tmp/DE_tmp --datasets ../moot/optimize/hpo/Health-ClosedPRs0010.csv --budget 50
