#!/bin/bash -l
#BSUB -J HEBO_FM-500-100-0.25-SAT-1_50
#BSUB -n 1
#BSUB -q short
#BSUB -W 120
#BSUB -o out_%J.log
#BSUB -e err_%J.log

source /usr/local/apps/miniconda20240526/etc/profile.d/conda.sh
conda activate /share/tjmenzie/kgangul/SEOptBench/smac_env

cd /share/tjmenzie/kgangul/SEOptBench/experiments
python3 experiment_runner_cluster.py --name HEBO --repeats 20 --runs_output_folder ../results/results_HEBO --logging_folder ../logging/logging_HEBO --output_directory ../results/tmp/HEBO_tmp --datasets ../moot/optimize/binary_config/FM-500-100-0.25-SAT-1.csv --budget 50
